"""002_add_database_defaults_and_constraints

Revision ID: 4b96206dcb32
Revises: 001
Create Date: 2025-11-26 20:28:28.112217

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks", "is_completed", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False
    )
    op.alter_column(
        "tasks", "priority", existing_type=sa.VARCHAR(), server_default=sa.text("'medium'"), existing_nullable=False
    )
    op.alter_column(
        "users", "is_active", existing_type=sa.BOOLEAN(), server_default=sa.text("true"), existing_nullable=False
    )
    op.alter_column(
        "users", "is_admin", existing_type=sa.BOOLEAN(), server_default=sa.text("false"), existing_nullable=False
    )

    # Add CHECK constraint for priority values
    op.create_check_constraint("task_priority_check", "tasks", "priority IN ('low', 'medium', 'high')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop CHECK constraint
    op.drop_constraint("task_priority_check", "tasks", type_="check")

    op.alter_column("users", "is_admin", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
    op.alter_column("users", "is_active", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
    op.alter_column("tasks", "priority", existing_type=sa.VARCHAR(), server_default=None, existing_nullable=False)
    op.alter_column("tasks", "is_completed", existing_type=sa.BOOLEAN(), server_default=None, existing_nullable=False)
    # ### end Alembic commands ###
